import {
  Book,
  Link,
  FileText,
  Video,
  Music,
  BarChart,
  Computer,
  Smartphone,
  Globe,
  FileImage,
  FileCog,
  FileCode,
  Package,
  Calendar,
  Mail,
  Users,
  Plane,
  PenTool,
  Palette,
  Headphones,
  Camera,
  CloudRain,
  Lock,
  Heart,
  Star,
  Map,
  Store,
  Zap,
  Radio,
  MessageCircle,
  User,
  Building,
  Archive,
  Database,
  ShoppingCart,
  Truck,
  Coffee,
  Briefcase,
  Banknote,
  LayoutDashboard,
  Settings,
} from "lucide-react";

export const AVAILABLE_ICONS = [
  { value: "book", label: "Book", icon: Book },
  { value: "link", label: "Link", icon: Link },
  { value: "file-text", label: "Document", icon: FileText },
  { value: "video", label: "Video", icon: Video },
  { value: "music", label: "Audio", icon: Music },
  { value: "bar-chart", label: "Chart", icon: BarChart },
  { value: "computer", label: "Computer", icon: Computer },
  { value: "smartphone", label: "Mobile", icon: Smartphone },
  { value: "globe", label: "Website", icon: Globe },
  { value: "file-image", label: "Image", icon: FileImage },
  { value: "file-cog", label: "Settings File", icon: FileCog },
  { value: "file-code", label: "Code", icon: FileCode },
  { value: "package", label: "Package", icon: Package },
  { value: "calendar", label: "Calendar", icon: Calendar },
  { value: "mail", label: "Email", icon: Mail },
  { value: "users", label: "Users", icon: Users },
  { value: "plane", label: "Travel", icon: Plane },
  { value: "pen-tool", label: "Design", icon: PenTool },
  { value: "palette", label: "Art", icon: Palette },
  { value: "headphones", label: "Audio Equipment", icon: Headphones },
  { value: "camera", label: "Photography", icon: Camera },
  { value: "cloud-rain", label: "Weather", icon: CloudRain },
  { value: "lock", label: "Security", icon: Lock },
  { value: "heart", label: "Health", icon: Heart },
  { value: "star", label: "Favorite", icon: Star },
  { value: "map", label: "Location", icon: Map },
  { value: "store", label: "Shop", icon: Store },
  { value: "zap", label: "Energy", icon: Zap },
  { value: "radio", label: "Broadcast", icon: Radio },
  { value: "message-circle", label: "Chat", icon: MessageCircle },
  { value: "user", label: "Profile", icon: User },
  { value: "building", label: "Organization", icon: Building },
  { value: "archive", label: "Archive", icon: Archive },
  { value: "database", label: "Database", icon: Database },
  { value: "shopping-cart", label: "Shopping", icon: ShoppingCart },
  { value: "truck", label: "Shipping", icon: Truck },
  { value: "coffee", label: "Food & Drink", icon: Coffee },
  { value: "briefcase", label: "Business", icon: Briefcase },
  { value: "banknote", label: "Finance", icon: Banknote },
  { value: "layout-dashboard", label: "Dashboard", icon: LayoutDashboard },
  { value: "settings", label: "Settings", icon: Settings },
];
